global:
  title: "Example 13: Generate and convert Copernicus-like NetCDF files to EMSO-compliant ERDDAP Dataset"
  summary: "Simple Copernicus-like dataset that will be converted on-the-fly to EMSO-compliant dataset using NcML and some tricks in datasets.xml"
  Conventions: "OceanSITES EMSO CF-1.8"
  institution: "UPC - Universitat Politècnica de Catalunya"
  institution_edmo_code: "2150"
  update_interval: "void"
  site_code: "OBSEA"
  emso_site: "OBSEA"
  emso_regional_facility: "Balearic Sea"
  source: "mooring"
  data_type: "OceanSITES profile data"
  format_version: "1.4"
  network: "EMSO"
  data_mode: "D"
  project: ""
  principal_investigator: "Homer Simpson"
  principal_investigator_email: "homer.simpson@fake.com"
  license: "CC-BY-4.0"
  featureType: "timeSeries" # VERY IMPORTANT: if featureType is not set explicitly to timeSeries and the lat/lon change over
                            # time, a trajectory type will be probably detected.

platforms:
  OBSEA_seabed_station:
    long_name: "OBSEA Seafloor Observatory"  # human-readable long name of the platform
    wmo_platform_code: "6103565"  # (optional) World Meteorological Organization platform number
    emso_platform: "OBSEA seabed station"  # link to the OSO ontology
    platform_type: "mooring"  # Platform type from the L06 vocabulary
    platform_type_uri: "http://vocab.nerc.ac.uk/collection/L06/current/48/"  # Link to an instance of the L06 vocabulary
    info_url: "https://obsea.es"  # (optional) uri where more information can be obtained
    # (optional) other relevant information
    comment: "OBSEA seafloor observatory is a multiparametric cabled observatory located at NW mediterranean sea"

    # Nominal coordinates, deployment variables or real-time GPS coordinates can be provided in the data with the
    # precise_latitude/precise_longitude variable, (standard name: deployment_latitude, P01 code: ALATGP01).
    latitude: 41.18212  # nominal latitude
    longitude: 1.75257  # nominal longitude

sensors:

  SBE16_SN57353_6479:
    long_name: "Sea-Bird Scientific SBE16"  # human-readable name
    sensor_serial_number: "57353_6479"
    sensor_mount: "mounted_on_mooring_line"  # mounting from a controlled list
    sensor_orientation: "upward"  # (optional) only relevant for ADCPs
    sdn_instrument_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1457"
    sensor_type_uri: "http://vocab.nerc.ac.uk/collection/L05/current/130/"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0013/"

variables:
  TEMP:
    long_name: "sea water temperature"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/TEMPST01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPAA/"
    standard_name: "sea_water_temperature"

  PRES:
    long_name: "sea water pressure"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/PRESPR01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPDB/"
    standard_name: "sea_water_pressure"

  CNDC:
    long_name: "sea water electrical conductivity"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/CNDCST01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UECA/"
    standard_name: "sea_water_electrical_conductivity"

  PSAL:
    long_name: "sea water salinity"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/PRESPR01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPDB/"
    standard_name: "sea_water_pressure"

  SVEL:
    long_name: "speed of sound in sea water"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/SVELCT01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UVAA/"
    standard_name: "speed_of_sound_in_sea_water"
