global:
  title: "Example 07: Two ADCPs, one mounted in a seabed station and another in a buoy"
  summary: "Two ADCPs, one mounted in a seabed station and another in a buoy"
  Conventions: "OceanSITES EMSO CF-1.8"
  institution: "UPC - Universitat Politècnica de Catalunya"
  institution_edmo_code: "2150"
  institution_ror_uri: "https://ror.org/03mb6wj31"
  update_interval: "void"
  emso_site_name: "OBSEA"
  emso_regional_facility_name: "Balearic Sea"
  source: "mooring"
  data_type: "OceanSITES profile data"
  format_version: "1.4"
  network: "EMSO"
  data_mode: "D"
  projects: "DIGI4ECO GEORGE"
  project_codes: "101112883 101094716"
  principal_investigator: "Homer Simpson"
  principal_investigator_email: "homer.simpson@fake.com"
  license: "CC-BY-4.0"
  contributors: "Bart Simpson, Peter Griffin, Rick Sánchez"
  contributor_types: "DataCollector DataManager Researcher"


platforms:
  OBSEA_seabed_station:
    long_name: "OBSEA seabed station"  # human-readable long name of the platform
    wmo_platform_code: "6103565"  # (optional) World Meteorological Organization platform number
    emso_platform_name: "OBSEA seabed station"  # link to the OSO ontology
    platform_type_name: "mooring"  # Platform type from the L06 vocabulary
    platform_type_uri: "http://vocab.nerc.ac.uk/collection/L06/current/48/"  # Link to an instance of the L06 vocabulary
    platform_reference: "https://obsea.es"  # (optional) uri where more information can be obtained
    # (optional) other relevant information
    comment: "The seafloor section of the OBSEA multiparametric cabled observatory seafloor observatory, located at NW mediterranean sea"

    # Nominal coordinates, deployment variables or real-time GPS coordinates can be provided in the data with the
    # precise_latitude/precise_longitude variable, (standard name: deployment_latitude, P01 code: ALATGP01).
    latitude: 41.18212  # nominal latitude
    longitude: 1.75257  # nominal longitude

sensors:
  AWAC_SN0001:
    long_name: "AWAC-AST 1MHz 0001"  # human-readable name
    sensor_serial_number: "0001"
    sensor_mount: "mounted_on_seafloor_structure"  # mounting from a controlled list
    sensor_orientation: "upward"  # (optional) only relevant for ADCPs
    sdn_instrument_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0897"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0068/"
    sensor_type_uri: "http://vocab.nerc.ac.uk/collection/L05/current/115/"
    sensor_reference: "https://www.nortekgroup.com/products/awac-1-mhz"

  AWAC_SN0002:
    long_name: "AWAC-AST 1MHz 0002"  # human-readable name
    sensor_serial_number: "0002"
    sensor_mount: "mounted_on_surface_buoy"  # mounting from a controlled list
    sensor_orientation: "downward"  # (optional) only relevant for ADCPs
    sdn_instrument_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOL0897"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0068/"
    sensor_type_uri: "http://vocab.nerc.ac.uk/collection/L05/current/115/"
    sensor_reference: "https://www.nortekgroup.com/products/awac-1-mhz"

variables:
  CSPD:
    long_name: "sea water speed"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/LCSAZZ01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UVBB/"
    standard_name: "sea_water_speed"

  CDIR:
    long_name: "sea water direction"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/LCDAAP01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/DEGN/"
    standard_name: "sea_water_velocity_to_direction"
