global:
  title: "Example 08: AUV trajectory with a CTD"
  summary: "AUV acquiring CTD data over a trajectory"
  Conventions: "OceanSITES EMSO CF-1.8"
  institution: "UPC - Universitat Politècnica de Catalunya"
  institution_edmo_code: "2150"
  update_interval: "void"
  site_code: "OBSEA"
  emso_facility: "OBSEA"
  source: "mooring"
  data_type: "OceanSITES profile data"
  format_version: "1.4"
  network: "EMSO"
  data_mode: "D"
  project: ""
  principal_investigator: "Homer Simpson"
  principal_investigator_email: "homer.simpson@fake.com"
  license: "CC-BY-4.0"

platforms:
  Girona500_SN0001:
    long_name: "Girona 500 AUV SN0001"  # human-readable long name of the platform
    wmo_number: ""  # (optional) World Meteorological Organization platform number
    emso_ontology_uri: ""  # link to the OSO ontology
    platform_type: "autonomous underwater vehicle"  # Platform type from the L06 vocabulary
    platform_type_uri: "http://vocab.nerc.ac.uk/collection/L06/current/25/"  # Link to an instance of the L06 vocabulary
    info_url: "https://iquarobotics.com/girona-500-auv"  # (optional) uri where more information can be obtained
    # (optional) other relevant information
    comment: "Girona 500 is an autonomous underwater vehicle with hovering capability for a maximum depth of 500m. The Girona 500 can be easily configured for multiple tasks thanks to a large payload volume and an open software architecture."

sensors:
  SBE37SMP_SN47472_5496:
    long_name: "Sea-Bird Scientific SBE37 SMP CTD Sensor"  # human-readable name
    sensor_serial_number: "37SMP47472-5496"
    sensor_mount: "mounted_on_glider"  # mounting from a controlled list
    sensor_orientation: "downward"  # (optional) only relevant for ADCPs
    sensor_model_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1457"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0013/"

variables:
  TEMP:
    long_name: "sea water temperature"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/TEMPST01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPAA/"
    standard_name: "sea_water_temperature"
  PRES:
    long_name: "sea water pressure"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/PRESPR01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPDB/"
    standard_name: "sea_water_pressure"

  CNDC:
    long_name: "sea water electrical conductivity"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/CNDCST01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UECA/"
    standard_name: "sea_water_electrical_conductivity"

  PSAL:
    long_name: "sea water salinity"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/PRESPR01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPDB/"
    standard_name: "sea_water_pressure"

  SVEL:
    long_name: "speed of sound in sea water"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/SVELCT01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UVAA/"
    standard_name: "speed_of_sound_in_sea_water"
