global:
  title: "Example 15: Dataset with an unknown sensor"
  summary: "Simple dataset with two CTDs, but the information regarding one of them as been lost"
  Conventions: "OceanSITES EMSO CF-1.8"
  institution: "UPC - Universitat Politècnica de Catalunya"
  institution_edmo_code: "2150"
  institution_ror_uri: "https://ror.org/03mb6wj31"
  update_interval: "void"
  emso_site_name: "OBSEA"
  emso_regional_facility_name: "Balearic Sea"
  source: "mooring"
  data_type: "OceanSITES profile data"
  format_version: "1.4"
  network: "EMSO"
  data_mode: "D"
  projects: "DIGI4ECO GEORGE"
  project_codes: "101112883 101094716"
  principal_investigator: "Homer Simpson"
  principal_investigator_email: "homer.simpson@fake.com"
  license: "CC-BY-4.0"
  contributors: "Bart Simpson, Peter Griffin, Rick Sánchez"
  contributor_types: "DataCollector DataManager Researcher"

platforms:
  OBSEA_seabed_station:
    long_name: "OBSEA seabed station"  # human-readable long name of the platform
    wmo_platform_code: "6103565"  # (optional) World Meteorological Organization platform number
    emso_platform_name: "OBSEA seabed station"  # link to the OSO ontology
    platform_type_name: "mooring"  # Platform type from the L06 vocabulary
    platform_type_uri: "http://vocab.nerc.ac.uk/collection/L06/current/48/"  # Link to an instance of the L06 vocabulary
    platform_reference: "https://obsea.es"  # (optional) uri where more information can be obtained
    # (optional) other relevant information
    comment: "The seafloor section of the OBSEA multiparametric cabled observatory seafloor observatory, located at NW mediterranean sea"

    # Nominal coordinates, deployment variables or real-time GPS coordinates can be provided in the data with the
    # precise_latitude/precise_longitude variable, (standard name: deployment_latitude, P01 code: ALATGP01).
    latitude: 41.18212  # nominal latitude
    longitude: 1.75257  # nominal longitude

sensors:
  SBE37SMP_SN47472_5496:
    long_name: "Sea-Bird Scientific SBE37 SMP CTD Sensor"  # human-readable name
    sensor_serial_number: "37SMP47472-5496"
    sensor_mount: "mounted_on_seafloor_structure"  # mounting from a controlled list
    sensor_orientation: "upward"  # (optional) only relevant for ADCPs
    sdn_instrument_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1457"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0013/"
    sensor_type_uri: "http://vocab.nerc.ac.uk/collection/L05/current/130/"
    sensor_reference: "https://www.seabird.com/moored/sbe-37-sm-smp-smp-odo-microcat/family?productCategoryId=54627473786"

  unknown:
    long_name: "Unknown sensor, this information has been lost"  # human-readable name
    sensor_serial_number: "n/a"
    sensor_mount: "mounted_on_mooring_line"  # mounting from a controlled list
    sensor_orientation: "upward"  # (optional) only relevant for ADCPs
    sdn_instrument_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOLZZZ"
    sensor_type_uri: "http://vocab.nerc.ac.uk/collection/L05/current/999/"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0002/"
    sensor_reference: ""
    comment: "This is dummy sensor variable is used when we do not know which sensor took the measurement"

variables:
  TEMP:
    long_name: "sea water temperature"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/TEMPST01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPAA/"
    standard_name: "sea_water_temperature"

  PRES:
    long_name: "sea water pressure"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/PRESPR01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPDB/"
    standard_name: "sea_water_pressure"

  CNDC:
    long_name: "sea water electrical conductivity"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/CNDCST01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UECA/"
    standard_name: "sea_water_electrical_conductivity"

  PSAL:
    long_name: "sea water salinity"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/PRESPR01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UPDB/"
    standard_name: "sea_water_pressure"

  SVEL:
    long_name: "speed of sound in sea water"
    sdn_parameter_uri: "http://vocab.nerc.ac.uk/collection/P01/current/SVELCT01"
    sdn_uom_uri: "http://vocab.nerc.ac.uk/collection/P06/current/UVAA/"
    standard_name: "speed_of_sound_in_sea_water"
