global:
  title: "Example 12: Acoustic recordings from a Hydrophone"
  summary: "Example of a list of recordings from a hydrophone at OBSEA"
  Conventions: "OceanSITES EMSO CF-1.8"
  institution: "UPC - Universitat Politècnica de Catalunya"
  institution_edmo_code: "2150"
  institution_ror_uri: "https://ror.org/03mb6wj31"
  update_interval: "void"
  emso_site_name: "OBSEA"
  emso_regional_facility_name: "Balearic Sea"
  source: "mooring"
  data_type: "OceanSITES profile data"
  format_version: "1.4"
  network: "EMSO"
  data_mode: "D"
  projects: "DIGI4ECO GEORGE"
  project_codes: "101112883 101094716"
  principal_investigator: "Homer Simpson"
  principal_investigator_email: "homer.simpson@fake.com"
  license: "CC-BY-4.0"
  contributors: "Bart Simpson, Peter Griffin, Rick Sánchez"
  contributor_types: "DataCollector DataManager Researcher"

platforms:
  OBSEA_seabed_station:
    long_name: "OBSEA Seafloor Observatory"  # human-readable long name of the platform
    wmo_platform_code: "6103565"  # (optional) World Meteorological Organization platform number
    emso_platform_name: "OBSEA seabed station"  # link to the OSO ontology
    platform_type_name: "mooring"  # Platform type from the L06 vocabulary
    platform_type_uri: "http://vocab.nerc.ac.uk/collection/L06/current/48/"  # Link to an instance of the L06 vocabulary
    platform_reference: "https://obsea.es"  # (optional) uri where more information can be obtained
    # (optional) other relevant information
    comment: "OBSEA seafloor observatory is a multiparametric cabled observatory located at NW mediterranean sea"

    # Nominal coordinates, deployment variables or real-time GPS coordinates can be provided in the data with the
    # precise_latitude/precise_longitude variable, (standard name: deployment_latitude, P01 code: ALATGP01).
    latitude: 41.18212  # nominal latitude
    longitude: 1.75257  # nominal longitude
    depth: 20


sensors:
  NAXYS_SN0010:
    long_name: "Bjørge-NAXYS Ethernet 02345 Hydrophone"  # human-readable name
    sensor_serial_number: "0010"
    sensor_mount: "mounted_on_seafloor_structure"  # mounting from a controlled list
    sensor_orientation: "upward"  # (optional) only relevant for ADCPs
    sdn_instrument_uri: "https://vocab.nerc.ac.uk/collection/L22/current/TOOL1593"
    sensor_manufacturer_uri: "http://vocab.nerc.ac.uk/collection/L35/current/MAN0144/"
    sensor_type_uri: "http://vocab.nerc.ac.uk/collection/L05/current/369/"
    sensor_reference: ""

variables:
  NOYS:
    long_name: "acoustics as flac files"
    comment: "acoustic recordings stored as FLAC files"
    sdn_parameter_uri: "https://vocab.nerc.ac.uk/collection/P01/current/AMBNSPL1"
    bits: "16"
    adc_reference_voltage: "+/- 2.5 V"
    sensitivity: "-192 dB re 1 uPa"
    preamplifier_gain: "20 dB"
    variable_type: "technical"


